ViewModels/GridCollectionItemViewModel.cs
using WebApp.Models.Entities;

namespace WebApp.ViewModels
{
    public class GridCollectionItemViewModel
    {
        public string Id { get; set; } = null!;
        public string? ImageUrl { get; set; } 
        public string Title { get; set; } = null!;
        public decimal Price { get; set; }
        public string? Description { get; set; }
        public CategoryEntity? Category { get; set; }

        public static implicit operator GridCollectionItemViewModel(ProductEntity productmodel) 
        {
            var item = new GridCollectionItemViewModel
            {
                Id = productmodel.Id.ToString(),
                Title = productmodel.Name,
                Price = productmodel.Price,
                ImageUrl = productmodel.ImageUrl,
                Description = productmodel.Description,
                Category = productmodel.Category,

            }; return item;
        }

    }
}

ViewModels/GridCollectionViewModel.cs
namespace WebApp.ViewModels;

public class GridCollectionViewModel
{
    public string? Title { get; set; } = "";
    public IEnumerable<string> Categories { get; set; } = null!;
    public IEnumerable<GridCollectionItemViewModel> GridCards { get; set; } = null!;
 
    public bool LoadMore { get; set; } = true;

}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")] //Behörighetsattribut för att bara tilldela åtkomst för användaren med admin rollen. 
    public class AdminController : Controller
    {
        private readonly UserRoleService _userRoleService;

        public AdminController(UserRoleService userRoleService)
        {
            _userRoleService = userRoleService;
        }

        public async Task<IActionResult> Index()
        {
            var userRoleList = await _userRoleService.GetAllUsersWithRolesAsync(); // Hämtar en lista med användare och deras roller genom att anropa GetAllUsersWithRolesAsync-metoden i UserRoleService.

            return View(userRoleList);  // Returnerar vyn med listan. 
        }


        // VG delar för att ändra och lägga till roller. 

        //[HttpPost]
        //public async Task<IActionResult> UpdateUserRole(string userId, string newRole)
        //{
        //    var result = await _userRoleService.UpdateUserRoleAsync(userId, newRole);
        //    if (result)
        //        return RedirectToAction("Index");

        //    // Handle error case
        //    return RedirectToAction("Index");
        //}
        //[HttpPost]
        //public async Task<IActionResult> AddUserRole(string userId, string role)
        //{
        //    var result = await _userRoleService.AddUserRoleAsync(userId, role);
        //    if (result)
        //        return RedirectToAction("Index");

        //    // Handle error case
        //    return RedirectToAction("Index");
        //}
        //[HttpPost]
        //public async Task<IActionResult> CreateRoleAsync(string roleName)
        //{
        //    var result = await _userRoleService.CreateRoleAsync(roleName);
        //    if (result)
        //        return RedirectToAction("Index");

        //    // Handle error case
        //    return RedirectToAction("Index");
        //}

    }

}

Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels;
using WebApp.Services;


namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactService _contactService;

        public ContactsController(ContactService contactService)
        {
            _contactService = contactService;
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactsViewModel contactsViewModel)
        {
            if (ModelState.IsValid)
            {
                _contactService.AddContact(contactsViewModel);

                return RedirectToAction("ThankYou");
            }

            return View(contactsViewModel);
        }

        public IActionResult ThankYou()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Contexts;
using WebApp.Models.Entities;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductService _productService;

        public ProductsController(ProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
           
            var viewModel = new ProductsIndexViewModel
            {
                AllProducts = new GridCollectionViewModel
                {
                    Title = "All Products",
                    GridCards = await _productService.GetAllProductsAsync()  // Hämtar alla produkter genom att anropa GetAllProductsAsync-metoden i ProductService.
                }
            };

            return View(viewModel);
        }



        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetProductByIdAsync(id); // Hämtar produkten via id:et genom att anropa GetProductByIdAsync-metoden i ProductService.

            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new ProductDetailsViewModel // Skapar en instans av ProductDetailsViewModel för att visa detaljer om produkten.
            {
                Id = Convert.ToInt32(product.Id),
                Name = product.Title,
                Price = product.Price,
                ImageUrl = product.ImageUrl,
                Description = product.Description,
                CategoryId = product.Category?.Id,
                Category = product.Category,
                RelatedDetailsList = await _productService.GetProductsAmountDetailsAsync(4) // Hämtar en lista med relaterade produktdetaljer genom att anropa GetProductsAmountDetailsAsync-metoden i ProductService. 
                                                                                           //Om jag vill ha en allmän metod som jag skall kunna hämta ut olika antal ifrån till en vy tar jag bara bort 4 och kör Take i vyn (Detailsvyn i detta fall) 
            };

            return View(viewModel);
        }

    }
}

Views/Partials/_Footer.cshtml
<footer class="footer">
    <div> 
        © @DateTime.Now.Year bmerketo. All right reserved. 
    </div>
</footer>

Views/Partials/_GridCollection.cshtml
@model GridCollectionViewModel



@if (Model != null)
{
    <section class="collection">
        <div class="container">
            @if (!string.IsNullOrEmpty(Model.Title))
            {
                <h1 class="collection-title">@Model.Title</h1>   // Kontrollerar om en titel har angetts och renderar den. 
            }
            
            @if (Model.Categories != null)
            {
                <ul class="categories">
                    @foreach (var category in Model.Categories)     // Kontrollerar om kategorier finns och renderar dem i en lista.
                    {
                        <li class="category-item">@category</li>
                    }

                </ul>
            }

            @if (Model.GridCards != null)       // Kontrollerar om GridCards finns och renderar dem.
            {
                <div class="collection-grid">
                    @foreach (var item in Model.GridCards)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                    }
                </div>
            }
            @if (Model.LoadMore)        // Kontrollerar om LoadMore är true och renderar.
            {
                <div class="load-more">
                    <button class="btn-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
                </div>
            }

        </div>
    </section>
}

Views/Partials/_GridCollectionItem.cshtml
@model GridCollectionItemViewModel

<a asp-controller="products" asp-action="details" asp-route-id="@Model.Id" class="collection-item">
    <img src="@Model.ImageUrl" alt="@Model.Title">
    <div class="body">
        <div class="info">
            <div class="title">@Model.Title</div>
            <div class="price">@Model.Price</div>
        </div>
        <i class="tocart fa-solid fa-cart-plus"></i>
    </div>
</a>

Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <div class="logo"><img src="/images/logo.svg" alt=""></div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-action="Index" asp-controller="Home">HOME</a>
            <a class="link" asp-action="Index" asp-controller="Products">PRODUCTS</a>
            <a class="link" asp-action="Contact" asp-controller="Contacts">CONTACT</a>
            @if (signInManager.IsSignedIn(User) && User.IsInRole("admin"))
            {
                <a class="link" asp-action="Index" asp-controller="Admin">ADMIN</a>
            }
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-action="Search" asp-controller="Products"><i class="fa-regular fa-search"></i></a>
            @if(signInManager.IsSignedIn(User))
            {   
                <a asp-action="Index" asp-controller="account">@User.Identity?.Name</a>
                <a asp-action="Index" asp-controller="account">@User.FindFirst("DisplayName")?.Value</a>
                <a class="link" asp-action="SignOut" asp-controller="Account">Sign Out</a>
            }
            else
            {
                <a class="link" asp-action="Register" asp-controller="Account">SignUp</a>
                <a class="link" asp-action="Login" asp-controller="Account">Login</a>
            }
            <a class="link" asp-action="Chart" asp-controller="Shopping"><i class="fa-solid fa-cart-shopping"></i></a>
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

Views/Partials/_Showcase.cshtml
@{
    var showcase = showcaseService.GetLatestShowcase();
}

@if(showcase != null)
{
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="ingress">@showcase?.Ingress</div>
                <div class="title">@showcase?.Title</div>

                @if (!string.IsNullOrEmpty(showcase?.Button?.Url) && !string.IsNullOrEmpty(showcase?.Button?.Content))
                {
                    <a href="@showcase?.Button?.Url" class="btn-theme">@showcase?.Button?.Content</a>
                }

            </div>
            <div class="content-image">
                <img src="@showcase?.ImageUrl" alt="@showcase?.Title" />
            </div>
        </div>
    </section>
}

Views/Partials/_Subscribe.cshtml
<section class="subscribe">
    <div class="container">
        <form>
            <input type="text" placeholder="subscribe email here...">
            <button class="btn-theme btn-rounded"><i class="fa-solid fa-rocket-launch"></i></i></button>
        </form>
    </div>
</section>

Views/Partials/_TopProducts.cshtml
@model GridCollectionViewModel

<section class="collection topsellingproducts">
    <div class="container">
        <div class="collection-grid">
            @if (Model.GridCards != null)
            {
                @foreach (var item in Model.GridCards)
                {
                    <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                }

            }
        </div>
    </div>
</section>

Views/Partials/_TopSellProducts.cshtml
@model GridCollectionViewModel

<section class="collection top-selling">
    <div class="container-fluid">
        <h1 class="collection-title">Top selling products this week!</h1>
        <div class="collection-grid">

            @if (Model.GridCards != null)
            {
                @foreach (var item in Model.GridCards)
                {
                    <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                }

            }
           
        </div>
        <div class="load-more">
            <button class="btn-white"><i class="fa-solid fa-chevron-left"></i></button>
            <button class="btn-white"><i class="fa-solid fa-chevron-right"></i></button>
        </div>
    </div>
</section>
<!-- top selling products end -->

Views/Partials/_UpToSale.cshtml
@model GridCollectionViewModel

<section class="up-to-sale">
    <div class="container">
        <div class="collection-grid">
            

            @if (Model.GridCards != null)
            {
                <div class="collection-grid">
                    @foreach (var item in Model.GridCards)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />   
                    }
                </div>
            }    
   
            <div  class="collection-item collection-content">
                <div class="container">
                    <div class="title-red">UP TO SALE</div>
                    <div class="title">50% OFF</div>
                    <div class="ingress">The Best Price Is Today</div>
                    <div class="text">Get the best daily offer, click on the link below!</div>
                    <a asp-controller="products" asp-action="details" class="link">Discover More</a>
                </div>
            </div>
        </div>
    </div>
</section>